---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require:
- mongoid
- rails
- nokogiri
- timetable
- rspec
- rspec/helper
- mongoid-rspec
- rails_helper
- factory_bot
- faker
domains: []
reporters:
- rubocop
- require_not_found
plugins:
- runtime
require_paths: []
max_files: 5000