---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require:
- mongoid
- uri
- open/http
- rails
- 'open-uri'
- nokogiri
- json
- timetable
domains: []
reporters:
- rubocop
- require_not_found
plugins:
- runtime
require_paths: []
max_files: 5000