development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      database: <%= Rails.app_class.parent_name %>_development
      hosts:
      - 127.0.0.1:27017
      options:
        connect_timeout: 15
production:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        connect_timeout: 15
test:
  clients:
    default:
      database: <%= Rails.app_class.parent_name %>_test
      hosts:
        - 127.0.0.1:27017
      options:
        connect_timeout: 15
